version: "3"
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  hbcase-backend:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - ./:/app
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
