version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:14
    working_directory: ~/repo

    steps:
      - checkout
      - setup-remote-docker

      - run: sudo npm i

      # build, lint, test!
      - run: npm run test

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
