# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: redis
      - image: circleci/node@14
    steps:
      - checkout
      - run:
        name: Run Tests
        command: npm run test
